site_name: D4vKry's Portfolio
site_url: https://d4vkry.github.io/
copyright: Copyright &copy; 2026 David Veiga (D4vKry). Licencia CC BY-NC-SA 4.0
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan

nav:
  - Inicio: index.md
  - Hack The Box - WriteUps:
    - 🔒 DevHub - Medium: HTB/DevHub/index.md
