site_name: D4vKry's Portfolio
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan

nav:
  - Inicio: index.md
  - Guías:
      - Firefox Hardening: guias/firefox-hardening/index.md
  - Hack The Box - WriteUps:
      - Easy:
          - Connected - Linux: HTB/Easy/Connected/index.md
          - Enigma - Linux: HTB/Easy/Enigma/index.md
      - Medium:
          - Checkpoint - Windows: HTB/Medium/Checkpoint/index.md
          - DevHub - Linux: HTB/Medium/DevHub/index.md
      - Hard:
          - Nimbus - Linux: HTB/Hard/Nimbus/index.md
