site_name: D4vKry's Portfolio
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan

nav:
  - Inicio: index.md
  - Hack The Box - WriteUps:
    - 🔒 DevHub - Medium: HTB/DevHub/index.md
